import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { servicePages } from "@/data/service-pages";
import { PageHero } from "@/components/ui/PageHero";
import { Container } from "@/components/layout/Container";
import { FeatureGrid, ProcessTimeline, CTASection, LinkStrip } from "@/components/ui/ContentBlocks";
import { DemoForm } from "@/components/forms/DemoForm";

export function generateStaticParams() { return servicePages.map(service => ({ slug: service.slug })); }
export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }): Promise<Metadata> { const { slug } = await params; const service = servicePages.find(item => item.slug === slug); return service ? { title: service.title, description: service.description, alternates: { canonical: `/services/${slug}` } } : {}; }
export default async function ServiceDetailPage({ params }: { params: Promise<{ slug: string }> }) { const { slug } = await params; const service = servicePages.find(item => item.slug === slug); if (!service) notFound(); return <main><PageHero eyebrow={service.eyebrow} title={service.title} description={service.description} image={slug === "inspection" ? "/images/property-house.webp" : "/images/property-commercial.webp"} breadcrumbs={[{ label: "Home", href: "/" }, { label: "Services", href: "/services" }, { label: service.eyebrow }]} /><LinkStrip links={[{ label: "Inspection", href: "/services/inspection" }, { label: "Due Diligence", href: "/services/due-diligence" }, { label: "Closing", href: "/services/closing" }, { label: "Construction", href: "/construction" }]} /><section className="bg-white py-18 sm:py-24"><Container className="grid gap-10 lg:grid-cols-[1.2fr_.8fr]"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-gold-dark">Service Overview</p><h2 className="mt-4 font-display text-4xl">Clarity, coordination and expert support</h2><p className="mt-6 max-w-3xl text-base leading-8 text-slate">{service.overview}</p>{service.disclaimer && <p className="mt-7 border-l-2 border-gold bg-sand p-5 text-sm leading-6 text-slate"><strong className="text-navy">Important:</strong> {service.disclaimer}</p>}</div><div className="bg-sand p-7"><p className="text-xs font-bold uppercase tracking-wider text-gold-dark">Who it is for</p><ul className="mt-5 space-y-3">{service.audiences.map(audience => <li key={audience} className="border-b border-navy/10 pb-3 text-sm font-semibold">{audience}</li>)}</ul></div></Container></section><FeatureGrid eyebrow="What is included" title={`${service.eyebrow} support`} items={service.features} /><ProcessTimeline title="A visible, coordinated process" steps={service.steps} />{service.form && <section className="bg-sand py-18 sm:py-24"><Container className="grid gap-12 lg:grid-cols-[.75fr_1.25fr]"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-gold-dark">Request Form</p><h2 className="mt-4 font-display text-4xl">{service.cta}</h2><p className="mt-4 text-sm leading-7 text-slate">Send a demo request now. No information will be permanently stored until the backend workflow is connected.</p></div><div className="bg-white p-7 sm:p-9"><DemoForm kind={service.form} submitLabel={service.cta} /></div></Container></section>}<CTASection title={service.cta} description="Start with a conversation. Our team will help clarify the next practical step." href={service.form ? "#request" : "/contact"} label={service.cta} /></main>; }
