import type { Metadata } from "next";
import { PageHero } from "@/components/ui/PageHero";
import { FeatureGrid, ProcessTimeline } from "@/components/ui/ContentBlocks";
import { Container } from "@/components/layout/Container";
import { DemoForm } from "@/components/forms/DemoForm";

export const metadata: Metadata = { title: "Sell Your Property", description: "Sell your property with professional presentation, inquiry support, negotiation assistance and closing coordination.", alternates: { canonical: "/sell" } };
const steps = [{ title: "Submit", description: "Share the property and your selling priorities." }, { title: "Review", description: "We organise the listing information and next steps." }, { title: "Verify", description: "Available information is reviewed before publication." }, { title: "Market", description: "The property is positioned for its intended audience." }, { title: "Negotiate", description: "Offers and commercial terms are coordinated clearly." }, { title: "Close", description: "Documentation and completion milestones come together." }];
const benefits = ["Professional presentation", "Qualified inquiries", "Marketing support", "Negotiation assistance", "Closing coordination"].map((title, index) => ({ title, description: ["Present the property's strongest story with consistent information.", "Focus time on more relevant property conversations.", "Coordinate thoughtful channels and listing content.", "Keep offers, questions and key terms visible.", "Connect the transaction through its final milestones."][index] }));
export default function SellPage() { return <main><PageHero eyebrow="AASAAN Selling" title="Sell Your Property. The AASAAN Way." description="A managed selling journey from first submission to coordinated closing." image="/images/property-house.webp" /><ProcessTimeline title="Six connected steps" steps={steps} /><FeatureGrid eyebrow="Why AASAAN Selling" title="Professional support around the sale" items={benefits} /><section id="list-property" className="bg-sand py-18 sm:py-24"><Container className="grid gap-12 lg:grid-cols-[.8fr_1.2fr]"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-gold-dark">Start here</p><h2 className="mt-4 font-display text-4xl sm:text-5xl">List My Property</h2><p className="mt-5 text-sm leading-7 text-slate">Complete the sample submission form. A live review workflow will be connected during the backend phase.</p><p className="mt-6 border-l-2 border-gold pl-5 text-sm font-semibold leading-6">All listings are subject to AASAAN review and approval before publication.</p></div><div className="bg-white p-6 sm:p-9"><DemoForm kind="listing" submitLabel="Submit Property" /></div></Container></section></main>; }
