import type { Metadata } from "next";
import { PageHero } from "@/components/ui/PageHero";
import { FeatureGrid, ProcessTimeline, CTASection } from "@/components/ui/ContentBlocks";
import { Container } from "@/components/layout/Container";
import { services } from "@/data/services";

export const metadata: Metadata = { title: "About AASAAN", description: "Learn about AASAAN's vision for one complete, connected property ecosystem.", alternates: { canonical: "/about" } };
const model = ["Discover", "Verify", "Transact", "Recover", "Build", "Invest", "Operate"].map((title, index) => ({ title, description: ["Find property and projects aligned with your needs.", "Understand the information, condition and documentation.", "Coordinate buying, selling, renting and closing.", "Navigate property-file and record challenges.", "Move from idea and plot to a managed project.", "Build knowledge before making investment decisions.", "Stay connected to the property after completion."][index] }));
const journey = ["Discover", "Evaluate", "Choose", "Transact", "Build / Improve", "Reinvest"].map((title, index) => ({ title, description: ["Start with location, purpose and priorities.", "Compare information, condition and fit.", "Make a considered selection.", "Coordinate documents and milestones.", "Create or improve the physical asset.", "Use better knowledge for the next decision."][index] }));
export default function AboutPage() { return <main><PageHero eyebrow="About AASAAN" title="Property Shouldn't Be Complicated." description="We are building the complete property ecosystem around one ambition: make property transactions and services genuinely Aasaan." image="/images/hero-property.webp" /><section className="bg-white py-18 sm:py-24"><Container className="grid gap-12 lg:grid-cols-2"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-gold-dark">Our Vision</p><h2 className="mt-4 font-display text-5xl">The Complete Property Ecosystem</h2></div><div className="space-y-5 text-base leading-8 text-slate"><p>Property journeys are rarely one transaction. Discovery leads to verification, documents, negotiation, closing, construction and the decisions that follow.</p><p>AASAAN connects specialist departments around that journey so customers can move with greater clarity, continuity and confidence.</p><blockquote className="border-l-2 border-gold pl-6 font-display text-2xl text-navy">One Ecosystem. One Property Journey. Made Aasaan.</blockquote></div></Container></section><FeatureGrid eyebrow="The Ecosystem Model" title="Connected around the customer" items={model} /><section className="bg-white py-18 sm:py-24"><Container><h2 className="font-display text-4xl">AASAAN Departments</h2><div className="mt-8 grid gap-px bg-navy/10 sm:grid-cols-2 lg:grid-cols-3">{services.map(service => <div key={service.name} className="bg-white p-5"><p className="font-semibold">{service.name}</p><p className="mt-1 text-xs text-slate">{service.description}</p></div>)}</div></Container></section><ProcessTimeline eyebrow="Customer Journey" title="From the first search to what comes next" steps={journey} /><CTASection title="Begin your property journey" description="Whatever stage you are at, AASAAN is designed to help connect the next step." /></main>; }
