import type { Metadata } from "next";
import { PageHero } from "@/components/ui/PageHero";
import { Container } from "@/components/layout/Container";
import { ProjectCollection } from "@/components/projects/ProjectCollection";
import { projects } from "@/data/projects";
import { CTASection } from "@/components/ui/ContentBlocks";
import { Icon } from "@/components/ui/Icons";

export const metadata: Metadata = { title: "NOC-Verified Real Estate Projects in Pakistan", description: "Explore real estate projects reviewed against AASAAN's regulatory and NOC verification policy.", alternates: { canonical: "/projects" } };
export default function ProjectsPage() { return <main><PageHero eyebrow="AASAAN Projects" title="NOC-Verified Real Estate Projects in Pakistan" description="Explore projects presented with clearer regulatory-status information and connected expert assistance." image="/images/project-towers.webp" /><section className="bg-offwhite py-16 sm:py-20"><Container><ProjectCollection projects={projects} /></Container></section><section className="bg-white py-18 sm:py-24"><Container className="grid gap-10 lg:grid-cols-[.8fr_1.2fr]"><div><span className="grid h-14 w-14 place-items-center bg-gold-pale text-gold-dark"><Icon name="shield" className="h-7 w-7" /></span><h2 className="mt-6 font-display text-4xl">How project verification works</h2></div><div className="space-y-5 text-sm leading-7 text-slate"><p>AASAAN Projects is designed to promote projects that satisfy our regulatory and NOC verification policy. We review available information against the relevant authority source and make the status visible.</p><p><strong className="text-navy">AASAAN is not a regulatory approving authority.</strong> Verification does not replace a customer's own legal, financial or technical advice, and status may change after review.</p><p>Sample projects in this public-site phase use clearly labelled placeholder regulatory details until official publisher data and source documents are connected.</p></div></Container></section><CTASection title="Need help comparing projects?" description="Speak with an AASAAN expert about location, inventory, documentation and the questions to ask before booking." /></main>; }
