import type { Metadata } from "next";
import { PageHero } from "@/components/ui/PageHero";
import { Container } from "@/components/layout/Container";
import { FeatureGrid, ProcessTimeline, CTASection, LinkStrip } from "@/components/ui/ContentBlocks";
import { Icon } from "@/components/ui/Icons";

export const metadata: Metadata = { title: "Property Services for Overseas Pakistanis", description: "Discover, inspect, verify, close and manage Pakistan property from anywhere.", alternates: { canonical: "/overseas-pakistanis" } };
const countries = ["United Arab Emirates", "Saudi Arabia", "United Kingdom", "United States", "Canada", "Qatar"];
export default function OverseasPage() { return <main><PageHero eyebrow="For Overseas Pakistanis" title="Pakistan Property. Managed From Anywhere." description="A connected path for discovering, evaluating and coordinating property while you are abroad." image="/images/hero-property.webp" /><LinkStrip links={[{ label: "AASAAN Closing", href: "/services/closing" }, { label: "Property Inspection", href: "/services/inspection" }, { label: "Due Diligence", href: "/services/due-diligence" }]} /><FeatureGrid eyebrow="Connected support" title="Your local property journey, made visible" items={[{ title: "Property Discovery", description: "Build a shortlist around your priorities and location context." }, { title: "Project Shortlisting", description: "Compare project information and suitable inventory." }, { title: "Inspection", description: "Receive structured visible-condition observations and photos." }, { title: "Due Diligence", description: "Coordinate available records, sources and specialist questions." }, { title: "Documentation", description: "Organise transaction paperwork and professional support." }, { title: "Closing", description: "Track milestones from selection through handover." }, { title: "Construction", description: "Coordinate project management and progress visibility." }, { title: "Updates", description: "Keep agreed actions and records accessible across distance." }]} columns={4} /><section className="bg-white py-18 sm:py-24"><Container><p className="text-xs font-bold uppercase tracking-[.2em] text-gold-dark">Where our customers are</p><h2 className="mt-4 font-display text-4xl">Built for Pakistanis worldwide</h2><div className="mt-10 grid gap-px bg-navy/10 sm:grid-cols-2 lg:grid-cols-3">{countries.map(country => <article key={country} className="flex items-center gap-4 bg-white p-6"><span className="grid h-11 w-11 place-items-center bg-sand text-gold-dark"><Icon name="globe" /></span><h3 className="font-display text-xl">{country}</h3></article>)}</div></Container></section><ProcessTimeline title="A transparent remote journey" steps={[{ title: "Brief", description: "Define property, location and service requirements." }, { title: "Shortlist", description: "Review suitable properties or projects." }, { title: "Evaluate", description: "Coordinate inspection, records and questions." }, { title: "Choose", description: "Confirm direction with appropriate advice." }, { title: "Close", description: "Track documentation, milestones and handover." }, { title: "Manage", description: "Coordinate agreed post-transaction needs." }]} /><CTASection title="Your team on the ground" description="Speak to AASAAN about a property journey you need to manage from overseas." /></main>; }
