import type { Metadata } from "next";
import { PageHero } from "@/components/ui/PageHero";
import { FeatureGrid, ProcessTimeline } from "@/components/ui/ContentBlocks";
import { Container } from "@/components/layout/Container";
import { DemoForm } from "@/components/forms/DemoForm";

export const metadata: Metadata = { title: "AASAAN Construction", description: "Residential and commercial construction coordination, project management and site supervision.", alternates: { canonical: "/construction" } };
const services = ["Residential Construction", "Commercial Construction", "Grey Structure", "Turnkey Construction", "Renovation", "Project Management", "Site Supervision", "Contractor Coordination"].map((title, index) => ({ title, description: ["Coordinate the journey from plot and brief to a completed home.", "Plan and coordinate workplaces, retail and commercial property.", "Structure the core construction scope and milestone visibility.", "Bring design, construction and finishing into a coordinated delivery plan.", "Improve an existing property through a clearly defined scope.", "Keep scope, decisions and milestones visible to the customer.", "Coordinate documented site observations and progress updates.", "Connect customers with suitable, vetted project partners."][index], icon: index < 2 ? "building" : "check" }));
export default function ConstructionPage() { return <main><PageHero eyebrow="AASAAN Construction" title="From Plot to Property. Made AASAAN." description="A project-management-led approach to construction, supervision and vetted-partner coordination." image="/images/hero-property.webp" /><FeatureGrid eyebrow="Construction Services" title="A coordinated path from brief to build" items={services} columns={4} /><ProcessTimeline title="How it works" steps={[{ title: "Consult", description: "Understand the site, brief, priorities and budget context." }, { title: "Define", description: "Set scope, roles, milestones and required specialists." }, { title: "Plan", description: "Coordinate design, approvals and procurement inputs." }, { title: "Build", description: "Manage delivery with visible progress and decisions." }, { title: "Review", description: "Coordinate observations, completion items and records." }, { title: "Handover", description: "Bring final information and handover together." }]} /><section className="bg-sand py-18 sm:py-24"><Container className="grid gap-12 lg:grid-cols-[.8fr_1.2fr]"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-gold-dark">Start a conversation</p><h2 className="mt-4 font-display text-4xl">Request a Construction Consultation</h2><p className="mt-5 text-sm leading-7 text-slate">AASAAN is positioned as a project manager and coordinator of vetted partners. Final specialist appointments and responsibilities will be defined per project.</p></div><div className="bg-white p-7 sm:p-9"><DemoForm kind="consultation" submitLabel="Request Consultation" /></div></Container></section></main>; }
