import Image from "next/image";
import Link from "next/link";
import type { Article } from "@/types/article";
import { Container } from "@/components/layout/Container";
import { Breadcrumbs } from "@/components/ui/Breadcrumbs";
import { ArticleCard } from "./ArticleCard";
import { articles } from "@/data/articles";

export function ArticleDetail({ article }: { article: Article }) {
  const base = article.kind === "news" ? "/news" : "/insights"; const related = articles.filter(item => item.slug !== article.slug && item.kind === article.kind).slice(0, 3);
  const schema = { "@context": "https://schema.org", "@type": "Article", headline: article.title, datePublished: article.date, dateModified: article.updatedDate, author: { "@type": "Organization", name: article.author }, image: `https://aasaan.com.pk${article.image}`, publisher: { "@type": "Organization", name: "AASAAN" } };
  return <main><Container className="py-7"><Breadcrumbs items={[{ label: "Home", href: "/" }, { label: article.kind === "news" ? "News" : "Insights", href: base }, { label: article.title }]} /></Container><article><header className="bg-offwhite pb-14 pt-10"><Container className="max-w-5xl"><p className="text-xs font-bold uppercase tracking-[.18em] text-gold-dark">{article.category}</p><h1 className="mt-5 font-display text-5xl leading-[1.07] sm:text-7xl">{article.title}</h1><p className="mt-6 max-w-3xl text-lg leading-8 text-slate">{article.summary}</p><div className="mt-7 flex flex-wrap gap-4 text-xs font-semibold text-slate"><span>{article.author}</span><time>{article.date}</time><span>Updated {article.updatedDate}</span></div></Container></header><Container className="max-w-5xl"><div className="relative aspect-[16/8] overflow-hidden bg-sand"><Image src={article.image} alt="" fill priority sizes="100vw" className="object-cover" /></div><div className="mx-auto max-w-3xl py-14"><div className="prose-copy">{article.body.map(paragraph => <p key={paragraph}>{paragraph}</p>)}<h2>What It Means for Buyers</h2><p>Use official records, property-specific information and appropriately qualified advice before making a commitment. AASAAN's role is to bring the journey into a clearer, more connected process.</p><h2>Source Authority</h2><p>{article.sourceAuthority ?? "Source references will be added through the live editorial workflow."}</p><div className="border border-navy/10 bg-sand p-5"><strong className="text-navy">Official source placeholder</strong><p className="mt-1 text-sm">No official document or external source is linked in this sample article.</p></div></div></div></Container></article><section className="bg-sand py-18 sm:py-24"><Container><h2 className="font-display text-4xl">Related Articles</h2><div className="mt-9 grid gap-7 md:grid-cols-2 lg:grid-cols-3">{related.map(item => <ArticleCard key={item.slug} article={item} />)}</div><Link href={base} className="mt-8 inline-flex text-xs font-bold uppercase tracking-wider text-gold-dark">View all {article.kind === "news" ? "news" : "insights"}</Link></Container></section><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }} /></main>;
}
