import type { Metadata } from "next";
import { PageHero } from "@/components/ui/PageHero";
import { Container } from "@/components/layout/Container";
import { PropertyBrowser } from "@/components/property/PropertyBrowser";
import { properties } from "@/data/properties";
import { FeatureGrid, CTASection } from "@/components/ui/ContentBlocks";
import { Button } from "@/components/ui/Button";

export const metadata: Metadata = { title: "Property for Rent in Pakistan", description: "Find residential and commercial rental properties or list a property for rent with AASAAN.", alternates: { canonical: "/rent" } };
export default function RentPage() { return <main><PageHero eyebrow="AASAAN Renting" title="Property for Rent in Pakistan" description="A clearer rental journey for tenants, landlords and professional occupiers." image="/images/project-towers.webp" /><section className="bg-white py-14"><Container className="grid gap-5 sm:grid-cols-2"><div className="border-l-2 border-gold bg-sand p-7"><h2 className="font-display text-3xl">Find a Rental</h2><p className="mt-3 text-sm leading-6 text-slate">Search residential and commercial spaces that match your requirements.</p><Button href="#rental-listings" variant="navy" className="mt-6">Browse Rentals</Button></div><div className="border-l-2 border-gold bg-sand p-7"><h2 className="font-display text-3xl">List Property for Rent</h2><p className="mt-3 text-sm leading-6 text-slate">Present your rental and connect with relevant tenant inquiries.</p><Button href="/list-property?purpose=rent" variant="outline" className="mt-6">List a Rental</Button></div></Container></section><section id="rental-listings" className="bg-offwhite py-16 sm:py-20"><Container><PropertyBrowser items={properties} purpose="For Rent" /></Container></section><FeatureGrid eyebrow="AASAAN Renting" title="Support on both sides of the rental" items={[{ title: "Listing Support", description: "Clear presentation for landlords and occupiers." }, { title: "Tenant Inquiries", description: "Coordinate more relevant rental conversations." }, { title: "Viewing Coordination", description: "Bring availability and access into one process." }, { title: "Rental Documentation", description: "Organise the documents supporting the agreement." }, { title: "Transaction Support", description: "Coordinate the journey through handover." }]} /><CTASection title="Renting. Made AASAAN." description="Explore the complete service for landlords and tenants." href="/services/renting" label="Explore AASAAN Renting" /></main>; }
